### ISSUE TITLE
Review: Formulierungen in Tutorial

### ISSUE THREAD

**Issue by andreasHausberger** [andreasHausberger/Taxperiment_MLW#31]
Bitte um Rückmeldung: Passt das Tutorial von den Formulierungen so? Kann das eh auf Deutsch sein?

**Comment by muellerm82** [comment]
Bitte Englisch. Ich habe es eh schon Formuliert, findest du im Google Docs: https://docs.google.com/document/d/1RsAuTE4zXJf9orSEEdBJ-_9ZWBg77aobVid0p-u_pl0/edit#heading=h.q8cwwt4lrxde
